### ISSUE TITLE
Headers

### ISSUE THREAD

**Issue by ariutta** [irhc/js-csvparser#1]
Nice API!

Just checking -- any plans to add code for parsing headers? Several libraries give the option to specify whether the first row is a header row, or if it's not, to specify names for the headers. It's easy to do, so I thought maybe you think this should not be part of the lib.

**Comment by ariutta** [comment]
Also, this is probably much harder to do well, but some parsers look at whether the first field in each column has a different datatype from the rest of the fields, in order to automatically determine whether there are headers present.

**Comment by ckprod** [comment]
Hi!
Thanks for the input. I don't have any header row(s) in my use cases. But it's a nice feature anyway. I'll give it a try in the next few days.

**Comment by ckprod** [comment]
v1.5.0
